### ISSUE TITLE
Spacebar toggles Improve OSM panel while writing comment.

### ISSUE THREAD

**Issue by erjiang** [Telenav/improveosm.org#20]
Steps to repro:

1. Select a reported issue
2. Go to comment text area in left panel.
3. Start typing. Every time you type space, the entire Improve OSM panel slides down or up. Makes it very annoying to type a comment.

Expected - spacebar hotkey should not toggle panel while writing a comment.

Google Chrome 54 on Mac OS X.

**Comment by afmenez** [comment]
The same thing happens to me on the Save panel, when I am typing the description of the changes.

**Comment by openbrian** [comment]
+1

**Comment by tudorg-telenav** [comment]
added a fix. can you confirm the issues are solved?
